### ISSUE TITLE
When restoring state I don't think token view should call listener methods

### ISSUE THREAD

**Issue by apkelly** [splitwise/TokenAutoComplete#101]
Hi,

In my app when a token is added I store it in an ArrayList (a DB would also have same problem), however when the view is restored and the tokens are restored too, the onTokenAdded method is called once again, which means the token is added to my list again.

It would be nice if during a restore, only the internal setup of the token view is restored but no listener methods are called.

Thanks,

Andy.

**Comment by mgod** [comment]
Hi Andy! Thanks for trying this out. If you just need a list of tokens, it's probably better to use the ```getObjects``` method on the token view rather than tracking them yourself. I had intended ```onTokenAdded``` to be a way to update your own interface in response to changes in the tokens. I don't think it's possible to change this behavior with the current infrastructure of the code.
