### ISSUE TITLE
TokenAutoComplete in listview adapter

### ISSUE THREAD

**Issue by sohayb** [splitwise/TokenAutoComplete#103]
Hello,
I'm trying to add the TokenAutoComplete view inside a list item view, for that i set it to focusable false and  focusable in touch mode also to false. Don't know if this is the best way to do it so need your help on this :)
the way I'm managing tokens for each item is like this: (as clear() is not working)
```java
            for(Object o : holder.hashtagsView.getObjects()){
                holder.hashtagsView.removeObject(o);
            }
            for(NavigationItem.Hashtag hashtag : news.hashtags){
                holder.hashtagsView.addObject(hashtag);
            }
```
also, how can I get an event when a token is tapped/clicked?

Thanks :+1:

**Comment by syrakozz** [comment]
+1

**Comment by mgod** [comment]
hmmmm... I don't think the current implementation of the TokenAutoComplete is going to be very happy being reused. I made a couple of initial design mistakes that are hard to correct (which is why you're having trouble with clear).

I think what you're doing is probably the best you'll get,  but it sounds like you're not making the field editable? You just want to get a response when the token is tapped, not let users add tokens?

**Comment by sohayb** [comment]
yeah, the only thing I want is for the user to be able to tap the token, it's like tags for a certain article.

**Comment by mgod** [comment]
I think if I were in your position, I'd steal the ViewSpan, TokenImageSpan classes, the onClick and replaceText code and use them as a guide to build your own TextView subclass. I think you'll find that less work than repurposing this.

If you do want to do this, the only way I can think to get a "click" event out for a token is to implement a custom view that overrides onSelected in the layout you use for your token view and use that to detect clicks.

**Comment by sohayb** [comment]
And here I thought it was going to be easy :/ 
okay will try that, thanks a lot :)
