### ISSUE TITLE
Add token even if not present in drop down list (Persons)

### ISSUE THREAD

**Issue by hackerspk** [splitwise/TokenAutoComplete#109]
Let me start by thanking you sir for this amazing library, you are the man. I am using 1.2.1 library to support previous android versions. There are couple of problems I am facing. Let me explain them by examples.

Persons list
abcde
abcdef
abcdefg
abcdefgh

1. If user wants to add some this which is not list for example "new word" how to allow him to do so?
2.  If user wants to add just "abc" how to allow him? because "abcde" will automatically selected from list.
3. If user writes something and not press "," then how to make it a valid token because there may be other tokens too in the TokenAutoComplete.

Thanks

**Comment by mgod** [comment]
I'm glad you like the library! For 1, you can implement defaultObject to return some kind of placeholder and implement an ```onTokenAdded``` callback to prompt the used to do something with the placeholder. For 2 and 3, these are fixed in the later versions and I don't have plans to back port them, though you might be able to build https://github.com/wdullaer/TokenAutoComplete/tree/doubletap_fix which I believe includes the fixes for making completions optional and completing remaining text when the field loses focus.
