### ISSUE TITLE
Keyboard not opens with setTextIsSelectable

### ISSUE THREAD

**Issue by SagarPanwala** [splitwise/TokenAutoComplete#122]
I have to open keyboard with completionView.setTextIsSelectable(true);
Here is my code , 

        completionView = (ContactsCompletionView)findViewById(R.id.searchView);
        completionView.setAdapter(adapter);
        completionView.setTokenListener(this);
        completionView.setTextIsSelectable(true);
        char[] splitChar = {',', ';', ' ' };
        completionView.setSplitChar(splitChar);

**Comment by mgod** [comment]
I'd intentionally disabled text selection because the underlying text object does not accurately represent the tokens in the field. Can you tell me a little more about what you're using selection for?

**Comment by SagarPanwala** [comment]
I'm trying to paste single and multiple emails.
Also want to support keyboard and with splichar.
So please help on this.

**Comment by mgod** [comment]
Ah, that's a somewhat different issue. Pasting into the field is currently not working, which I see you're commenting on in #95. Rather than enabling text selection, call ```setLongClickable(true)``` which will let you pull up the paste menu item without letting you select text. I have some time to look into this today. How far into implementation are you?

**Comment by SagarPanwala** [comment]
Actually , I didn't get any success.I'm trying to achieve pasting and token with single and multiple email.

**Comment by mgod** [comment]
I haven't solved this (pasting emails is a little more complicated than I anticipated), but I'm marking this as a dup of #95
