### ISSUE TITLE
Pressing delete does not delete token in collapsed mode.

### ISSUE THREAD

**Issue by dschuermann** [splitwise/TokenAutoComplete#195]
When not using any specific TokenDeleteStyle the token is not deleted when pressing delete on the keyboard. Instead the classname is shown.

To reproduce:
1. Add many tokens
2. Focus different view to get the TokenAutoComplete to collapse (e.g., +3 is shown when 3 tokens do not fit inside the widget size).
3. Re-focus TokenAutoComplete
4. Delete one token

Our corresponding issue is here (including a screenshot): https://github.com/open-keychain/open-keychain/issues/1636

**Comment by Valodim** [comment]
Can also reproduce as:
1. add token
2. trigger activity recreation (development option -> don't keep activities)
3. delete token

**Comment by mgod** [comment]
This is expected behavior. It looks like overriding ```toString``` isn't an option in your case, so I'd pick a different delete style.

**Comment by dschuermann** [comment]
Hmm, I don't understand this behavior. According to the docs, ``TokenCompleteTextView.TokenDeleteStyle.Clear`` is the default deletion style and this should let the tokens disappear on deletion. This is not working, instead the classname is inserted as a string on deletion.

**Comment by mgod** [comment]
That's not good. I know there are some cases where the default behavior happens when restoring instance state, but I've usually seen it where it replaces the text with whatever the user entered when searching, not the ```toString``` value. Is there any chance you can log the output of ```getText``` on the token view after restoring instance state and then after deleting the token?
