### ISSUE TITLE
Input type, no completion, leaving before completion, remove all objects, custom delimiter

### ISSUE THREAD

**Issue by fikr4n** [splitwise/TokenAutoComplete#26]
I don't know if I should split this into 5 issues or just wrap them into this one issue :).

1. Calling `setInputType(int)` in `init()` makes `android:inputType` in XML layout ignored, doesn't it? Sometime I want to set my `inputType` in the XML layout.
2. Suggestion: how about adding an option to make user input as it be, so if the user doesn't click any item in the completion list, the token is the entered one.
3. When user leaves the view before making it a token (by pressing ",") it does not become a token.
4. Suggestion: how about adding such `removeAllObjects()` method besides `removeObject(Object)`.
5. Suggestion: how about making the delimiter (currently ",") as an option/variable.

**Comment by mgod** [comment]
Everything except 1 should be fixed in [1.3.0](https://github.com/splitwise/TokenAutoComplete/releases)

I did change the behavior on ```setInputType``` to add ```InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS``` and  ```InputType.TYPE_TEXT_FLAG_AUTO_COMPLETE``` on top of whatever you have set. I might reduce that to just autocomplete, as it sounds like disabling suggestions is not correct, but I'm not quite sure how to test it, so I'm going to close this out. If someone does run into issues with both of these being added, please open a new issue.
