### ISSUE TITLE
Request: refactor to onTokenAdded(View view, Object token)

### ISSUE THREAD

**Issue by REWmitenko** [splitwise/TokenAutoComplete#302]
Hey guys,
This is an extremely useful library and thanks for putting it up!

I'd like to be able to differentiate which TokenCompleteTextView is notifying me when onTokenAdded is called (is it the 'To' email field or the 'CC' email field?). 

Unless I'm missing something, could you please add the view that invokes this callback in the callback method.

**Comment by mgod** [comment]
I think probably the better solution is to use two separate delegates instead of trying to make one delegate figure out which field it's for. I'd rather not expose the view here in the API because it limits my internal implementation choices and this is one of the places where I'm likely to need to make a lot of changes to fix some long standing bugs.

**Comment by REWmitenko** [comment]
All right, that's the implementation I'm currently using
