### ISSUE TITLE
Any ideas on how to implement drag & drop on tokens?

### ISSUE THREAD

**Issue by awhlee** [splitwise/TokenAutoComplete#304]
Imagine an email app and you want to drag a completed token from To: to CC:

Thanks in advance.
--Tony

**Comment by mgod** [comment]
Hi Tony! Thanks for your interest in this project. Unfortunately, I don't think this project is a good fit for dragging and dropping. The underlying implementation doesn't really allow for arbitrary interactions and view repositioning in a reasonable way. I think you'll have much better luck looking at something where the chips are actually handled as separate views in a ```ViewGroup``` instead of images in an ```EditText``` as this library is implemented.
