### ISSUE TITLE
onTokenRemoved method called twice when calling clear method

### ISSUE THREAD

**Issue by maheshwariaanchal** [splitwise/TokenAutoComplete#357]
Whenever I call clear method on ContactsCompletionView (ContactsCompletionView.clear()), onTokenRemoved is called twice for removing single token. So if I have selected 6 tokens and I call clear method on ContactsCompletionView, onTokenRemoved is called 12 times. (Twice for a single token). 
Please help

**Comment by mgod** [comment]
It looks like this is a limitation of the current library. I'm working on an update that should change the underlying implementation enough to fix this issue, but I'm not sure when it will be available. In general, we recommend using `removeObject` on the objects you want to remove rather than `clear`.
