### ISSUE TITLE
Text field copying previous values when using retrofit to provide results

### ISSUE THREAD

**Issue by dragossusi** [splitwise/TokenAutoComplete#367]
For new 3.0.0-alpha when i use retrofit to populate adapter for autocomplete and i write something, the current text in edittext acts weird as i type:
if i write message with keyboard it goes like
m
mme
mmemes
mmemesmess
mmemesmessmessa
mmemesmessmessamessag
mmemesmessmessamessagmessage

**Comment by mgod** [comment]
Are you able to reproduce this with your device by installing the sample app from `master`? This is much more likely to be a keyboard/OS combination that enters input oddly than anything related to retrofit.

**Comment by mgod** [comment]
I can't think of any reason repopulating the adapter in any way would cause trouble with the text input. I'm still pretty sure this is going to turn out to be a keyboard/OS issue rather than anything to do with retrofit, but I can't reproduce this issue myself. Can you point me to a code sample and some instructions on how to get this to happen?
