### ISSUE TITLE
Update to 3.0.1 missing PartialCompletion

### ISSUE THREAD

**Issue by kroobroeck** [splitwise/TokenAutoComplete#394]
I just update from 2.0.8 to 3.0.1 and I am missing the ablity for partial completion. Meaning when I want remove some characters of the recognized token the whole token is delete at this moment. While partial completion would not let the token be deleted but the individual characters.

How can we implement this behaviour with the current newest version of the lib?

**Comment by mgod** [comment]
Unfortunately, I removed this option because I could not figure out how to build and maintain this behavior across all Android varieties. You could try to add some kind of text replacement behavior using the `onTokenRemoved` listener object, but I found that this was impossible to reliably maintain.
